##
# Code auto-generated by Visual Alchemist version {version}
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Date, String, Text, Float, ForeignKey
from sqlalchemy.dialects.mysql import BIGINT
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy.orm import sessionmaker, relationship, backref

Base = declarative_base()
{body}
if __name__ == '__main__':
	print('running sqlalchemy ' + sqlalchemy.__version__)
	engine = create_engine(r'sqlite:///visualalchemist.db', echo=True) #connect to database
	Base.metadata.create_all(engine) #Lets create the actual sqlite database and schema!
	print('database created: visualalchemist.db')
